config:
  provider: vsphere
  version: 4.8.9
  base_domain: rhtrva.internal
  cluster_name: ocp
  fips: false
  networkType: OVNKubernetes
  #isolationMode: Multitenant
  installer_ssh_key: "{{ lookup('file', '/home/amelie/ocp/config/ocp4lab.pub') }}"
  pull_secret: "{{ lookup('file', '/home/amelie/ocp/config/phil-pull-secret.txt') }}"
vcenter:
  ip: 192.168.10.5
  datastore: datastore1
  network_master: ocp4-master
  network_worker: ocp4-worker
  service_account_username: administrator@vsphere.local
  service_account_password: XXXX
  admin_username: administrator@vsphere.local
  admin_password: XXXX
  datacenter: ric1
  folder_absolute_path:
  vm_power_state: poweredon
  template_name: rhcos-vmware
download:
  clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ config.version }}
  dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest
  govc: https://github.com/vmware/govmomi/releases/download/v0.23.0/govc_linux_amd64.gz
bootstrap_vms:
  - { name: "bootstrap", ipaddr: "10.0.200.110", cpu: 4, ram: 16384, datastore: "datastore1"}
master_vms:
  - { name: "master0", ipaddr: "10.0.200.100", cpu: 4, ram: 16384, datastore: "datastore1"}
  - { name: "master1", ipaddr: "10.0.200.101", cpu: 4, ram: 16384, datastore: "datastore1"}
  - { name: "master2", ipaddr: "10.0.200.102", cpu: 4, ram: 16384, datastore: "datastore1"}
worker_vms:
  - { name: "worker0", ipaddr: "10.0.100.100", cpu: 4, ram: 8192, datastore: "datastore1"}
  - { name: "worker1", ipaddr: "10.0.100.101", cpu: 4, ram: 8192, datastore: "datastore1"}
#  - { name: "worker2", ipaddr: "192.168.86.187", cpu: 4, ram: 16384}
static_ip:
  gateway_master: 10.0.200.254
  gateway_worker: 10.0.100.254
  netmask_master: 255.255.255.0
  netmask_worker: 255.255.255.0
  dns: 192.168.10.23
  network_interface_name: eth0
network_modifications:
  enabled: true
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - cidr: 172.30.0.0/16
  machineNetwork:
  - cidr: 10.0.100.0/24
  - cidr: 10.0.200.0/24
ntp:
  custom: false
  ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
proxy:
  enabled: false
  http_proxy: http://helper.ocp4.example.com:3129
  https_proxy: http://helper.ocp4.example.com:3129
  no_proxy: example.com
  cert_content: |
    -----BEGIN CERTIFICATE-----
        <certficate content>
    -----END CERTIFICATE-----