---
- hosts: all
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Remove VMs
      import_role:
        name: remove_vms